export const cards = [
  {
    id: 1,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 2,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 3,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 5,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 6,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 7,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 8,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 9,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 10,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 11,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 12,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
  {
    id: 13,
    title: "Median of Two Sorted Arrays",
    source: "leetcode",
    tags: ["Algorithms", "DataBase", "Hash"],
    date: "2 days ago",
  },
];
