export const ADD_NEW_SOLUTION_REQUEST = "ADD_NEW_SOLUTION_REQUEST";
export const ADD_NEW_SOLUTION_SUCCESS = "ADD_NEW_SOLUTION_SUCCESS";
export const ADD_NEW_SOLUTION_FAIL = "ADD_NEW_SOLUTION_FAIL";
export const RESET_ADD_NEW_SOLUTION_ERROR = "RESET_ADD_NEW_SOLUTION_ERROR";
