export const DELETE_ONE_SOLUTION_FOR_AUTH_REQUEST =
  "DELETE_ONE_SOLUTION_FOR_AUTH_REQUEST";
export const DELETE_ONE_SOLUTION_FOR_AUTH_SUCCESS =
  "DELETE_ONE_SOLUTION_FOR_AUTH_SUCCESS";
export const DELETE_ONE_SOLUTION_FOR_AUTH_FAIL =
  "DELETE_ONE_SOLUTION_FOR_AUTH_FAIL";
