export const GET_ALL_SOLUTIONS_FOR_AUTH_USER_REQUEST =
  "GET_ALL_SOLUTIONS_FOR_AUTH_USER_REQUEST";
export const GET_ALL_SOLUTIONS_FOR_AUTH_USER_SUCCESS =
  "GET_ALL_SOLUTIONS_FOR_AUTH_USER_SUCCESS";
export const GET_ALL_SOLUTIONS_FOR_AUTH_USER_FAIL =
  "GET_ALL_SOLUTIONS_FOR_AUTH_USER_FAIL";
