export const GET_ONE_SOLUTION_DETAILS_REQUEST =
  "GET_ONE_SOLUTION_DETAILS_REQUEST";
export const GET_ONE_SOLUTION_DETAILS_SUCCESS =
  "GET_ONE_SOLUTION_DETAILS_SUCCESS";
export const GET_ONE_SOLUTION_DETAILS_FAIL = "GET_ONE_SOLUTION_DETAILS_FAIL";
