export const USER_LOGIN_WITH_GOOGLE_REQUEST = "USER_LOGIN_WITH_GOOGLE_REQUEST";
export const USER_LOGIN_WITH_GOOGLE_SUCCESS = "USER_LOGIN_WITH_GOOGLE_SUCCESS";
export const USER_LOGIN_WITH_GOOGLE_FAIL = "USER_LOGIN_WITH_GOOGLE_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
